/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACarousel: typeof import('@arco-design/web-vue')['Carousel']
    ACarouselItem: typeof import('@arco-design/web-vue')['CarouselItem']
    ActivityFeed: typeof import('./src/components/ActivityFeed.vue')['default']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    Announcements: typeof import('./src/components/Announcements.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    Challenges: typeof import('./src/components/Challenges.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCalendar: typeof import('@arco-design/web-vue/es/icon')['IconCalendar']
    IconClockCircle: typeof import('@arco-design/web-vue/es/icon')['IconClockCircle']
    IconCode: typeof import('@arco-design/web-vue/es/icon')['IconCode']
    IconDelete: typeof import('@arco-design/web-vue/es/icon')['IconDelete']
    IconEdit: typeof import('@arco-design/web-vue/es/icon')['IconEdit']
    IconHome: typeof import('@arco-design/web-vue/es/icon')['IconHome']
    IconLayers: typeof import('@arco-design/web-vue/es/icon')['IconLayers']
    IconMessage: typeof import('@arco-design/web-vue/es/icon')['IconMessage']
    IconMoon: typeof import('@arco-design/web-vue/es/icon')['IconMoon']
    IconNotification: typeof import('@arco-design/web-vue/es/icon')['IconNotification']
    IconPoweroff: typeof import('@arco-design/web-vue/es/icon')['IconPoweroff']
    IconPublic: typeof import('@arco-design/web-vue/es/icon')['IconPublic']
    IconRefresh: typeof import('@arco-design/web-vue/es/icon')['IconRefresh']
    IconRight: typeof import('@arco-design/web-vue/es/icon')['IconRight']
    IconSearch: typeof import('@arco-design/web-vue/es/icon')['IconSearch']
    IconSettings: typeof import('@arco-design/web-vue/es/icon')['IconSettings']
    IconSound: typeof import('@arco-design/web-vue/es/icon')['IconSound']
    IconStar: typeof import('@arco-design/web-vue/es/icon')['IconStar']
    IconSun: typeof import('@arco-design/web-vue/es/icon')['IconSun']
    IconTag: typeof import('@arco-design/web-vue/es/icon')['IconTag']
    IconThunderbolt: typeof import('@arco-design/web-vue/es/icon')['IconThunderbolt']
    IconTrophy: typeof import('@arco-design/web-vue/es/icon')['IconTrophy']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
